before_install:
  - git submodule update --init --recursive
language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - mysql -u root -e "create database twitdb_test; create user 'test' identified by 'password'; grant all privileges on twitdb_test.* to 'test';"
script: phpunit tests/AllTests.php
